[tool.poetry]
name = "blog"
version = "1.0.0"
description = "Kevin Deldycke's personal blog."
license = 'CC-BY-NC-SA-4.0'
authors = ["Kevin Deldycke <kevin@deldycke.com>"]
readme = "readme.md"
homepage = 'https://kevin.deldycke.com'
repository = 'https://github.com/kdeldycke/kevin-deldycke-blog'

[tool.poetry.urls]
"Funding" = "https://github.com/sponsors/kdeldycke"

[tool.poetry.dependencies]
python = "^3.8"
pelican = {extras = ["Markdown"], version = "^4.5.0"}
pymdown-extensions = "^8.0"
typogrify = "^2.0.7"
beautifulsoup4 = "^4.9.3"
mdx_video = "^0.1.8"
mdx_titlecase = "^1.2.0"
plumage = {git = "https://github.com/kdeldycke/plumage.git", branch = "develop"}
pygments = "^2.7.1"
pelican-sitemap = "^1.0.2"
pelican-neighbors = "^1.1.0"
pelican-thumbnailer = "^1.0.0"
pelican-tipue-search = {git = "https://github.com/pelican-plugins/tipue-search.git", branch = "migrate"}
gensim = "^3.8.3"

[tool.poetry.dev-dependencies]

[tool.black]
target-version = ['py38']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
