name: Labels
on:
  # Only the default branch has authority on the project management. This will
  # prevent any other tagging or release activity interfer with the project.
  push:
    branches:
      - master

jobs:

  labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Sync labels
      uses: lannonbr/issue-label-manager-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
