name: Lint
"on":
  push:
  pull_request:

jobs:

  lint-python:
    name: Lint and check Python code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-python@v2.1.3
        with:
          python-version: '3.8'
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Lint
        run: |
          poetry run pycodestyle
          poetry run pylint

  lint-yaml:
    name: Lint YAML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-python@v2.1.3
        with:
          python-version: '3.8'
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Lint
        run: |
          poetry run yamllint .

  lint-html:
    # Provides hints to fix theme's templates.
    name: Lint HTML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
        with:
          submodules: true
      - uses: actions/setup-python@v2.1.4
        with:
          python-version: '3.8'
      - name: Install Pelican
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install
      - name: Build HTML pages
        run: |
          poetry run pelican --verbose --settings ./publishconf.py ./content
      - name: Install HTMLHint
        run: |
          sudo npm install htmlhint -g
      - name: Lint
        run: |
          htmlhint ./output/**/*.html
