# Sources:
#   * https://calibreapp.com/blog/compress-images-in-prs/
#   * https://github.com/marketplace/actions/image-actions

name: Optimize images
on: [push, pull_request]

jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
