name: Test
on:
  push:
  pull_request:
  schedule:
    # Run tests every Monday at 9:17 to catch regressions.
    - cron: "17 9 * * 1"

jobs:

  test:
    name: Generate the static site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.3
      with:
        submodules: true
    - uses: actions/setup-python@v2.1.3
    - name: Install Pelican
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        poetry install
    - name: Build website
      run: |
        poetry run pelican --verbose ./content
